/**
 * Catalogue seed data.
 *
 * tuple shape: [title, artist, album, releaseYear, durationSec, genre, moods]
 * moods is a comma separated string that we split on write.
 *
 * NOTE: this is a demo library — the audio stream attached to every record is a
 * placeholder preview clip, the metadata (title / artist / album) is the real
 * catalogue information used for browsing, search, charts and playlists.
 */

export type RawTrack = [
  title: string,
  artist: string,
  album: string,
  year: number,
  durationSec: number,
  genre: string,
  moods: string,
];

export const PUNJABI_TRACKS: RawTrack[] = [
  ["Lover", "Diljit Dosanjh", "Lover", 2024, 191, "pop", "romance,dance,new"],
  ["Born to Shine", "Diljit Dosanjh", "Moonchild Era", 2021, 214, "hip-hop", "flex,party,anthem"],
  ["G.O.A.T", "Diljit Dosanjh", "G.O.A.T", 2020, 235, "hip-hop", "flex,anthem"],
  ["Peaches", "Diljit Dosanjh", "Peaches", 2021, 190, "pop", "chill,summer,romance"],
  ["Lemonade", "Diljit Dosanjh", "Moonchild Era", 2021, 201, "pop", "chill,summer"],
  ["Channni", "Diljit Dosanjh", "Moonchild Era", 2021, 226, "folk-pop", "soulful,night"],
  ["Naram Kalija", "Diljit Dosanjh", "Chamkila", 2024, 244, "folk", "soulful,new,cinema"],
  ["Ishq Mitaye", "Diljit Dosanjh", "Chamkila", 2024, 218, "folk", "soulful,new,cinema"],
  ["Jind Mahi", "Diljit Dosanjh", "Jind Mahi", 2022, 207, "folk-pop", "romance,wedding"],
  ["Excuses", "AP Dhillon", "Hidden Gems", 2020, 202, "r&b", "chill,late-night,party"],
  ["Brown Munde", "AP Dhillon", "Brown Munde", 2020, 216, "hip-hop", "party,flex,anthem"],
  ["Laembadgini", "AP Dhillon", "Laembadgini", 2022, 208, "dance", "party,bhangra,roadtrip"],
  ["Desires", "AP Dhillon", "Desires", 2023, 195, "r&b", "chill,late-night"],
  ["Summer High", "AP Dhillon", "Summer High", 2023, 188, "pop", "summer,roadtrip,party"],
  ["Insane", "AP Dhillon", "Insane", 2021, 205, "hip-hop", "party,flex"],
  ["Runaway", "AP Dhillon", "Hidden Gems", 2020, 197, "r&b", "late-night,mood"],
  ["295", "Sidhu Moose Wala", "Moosetape", 2021, 250, "hip-hop", "raw,anthem,mood"],
  ["The Last Ride", "Sidhu Moose Wala", "Moosetape", 2021, 226, "hip-hop", "dark,mood,anthem"],
  ["Levels", "Sidhu Moose Wala", "Moosetape", 2021, 233, "hip-hop", "flex,party"],
  ["Legend", "Sidhu Moose Wala", "Legend", 2019, 209, "hip-hop", "anthem,flex"],
  ["So High", "Sidhu Moose Wala", "So High", 2017, 220, "hip-hop", "classic,flex"],
  ["Bambiha Bole", "Sidhu Moose Wala", "Bambiha Bole", 2020, 244, "hip-hop", "raw,mood"],
  ["Sanju", "Sidhu Moose Wala", "Sanju", 2021, 231, "hip-hop", "storytelling,mood"],
  ["Cheques", "Shubh", "Still Rollin", 2023, 190, "hip-hop", "flex,new,party"],
  ["Still Rollin", "Shubh", "Still Rollin", 2023, 176, "hip-hop", "anthem,flex"],
  ["King Shit", "Shubh", "King Shit", 2023, 184, "hip-hop", "flex,party"],
  ["No Love", "Shubh", "No Love", 2022, 197, "hip-hop", "heartbreak,mood"],
  ["Elevator", "Shubh", "Elevator", 2022, 181, "hip-hop", "flex,party"],
  ["One Love", "Shubh", "One Love", 2024, 189, "hip-hop", "new,anthem"],
  ["Adhiya", "Karan Aujla", "Adhiya", 2023, 203, "folk-pop", "romance,wedding,party"],
  ["Hint", "Karan Aujla", "Hint", 2024, 195, "pop", "romance,new"],
  ["52 Bars", "Karan Aujla", "52 Bars", 2022, 213, "hip-hop", "raw,flex"],
  ["Chitta", "Karan Aujla", "Chitta", 2022, 199, "hip-hop", "dark,mood"],
  ["Don't Look", "Karan Aujla", "Don't Look", 2021, 207, "dance", "party,dance"],
  ["Saza-E-Maut", "Karan Aujla", "Saza-E-Maut", 2023, 224, "hip-hop", "dark,anthem"],
  ["Pyaar Mangdi", "Jordan Sandhu", "Pyaar Mangdi", 2021, 226, "folk-pop", "romance,wedding"],
  ["Sochan", "Amrit Maan", "Sochan", 2021, 218, "folk", "desi,party"],
  ["Laung Laachi", "Gurnam Bhullar", "Laung Laachi", 2018, 231, "folk-pop", "romance,wedding"],
  ["Bijlee Bijlee", "Harrdy Sandhu", "Bijlee Bijlee", 2022, 199, "dance", "party,dance,new"],
  ["Yaar Ni Milya", "Harrdy Sandhu", "Yaar Ni Milya", 2019, 214, "pop", "heartbreak,romance"],
  ["Sip Sip", "Jasmine Sandlas", "Sip Sip", 2021, 205, "dance", "party,dance"],
  ["Daru Badnam", "Kamal Khan", "Daru Badnam", 2019, 222, "folk-pop", "party,desi"],
  ["Qismat", "Ammy Virk", "Qismat", 2018, 249, "pop", "romance,soulful,cinema"],
  ["Filhall", "B Praak", "Filhall", 2019, 234, "pop", "romance,soulful"],
  ["Ishare Tere", "Guru Randhawa", "Ishare Tere", 2019, 187, "pop", "romance,dance"],
  ["Sanu Ik Pal", "Rahat Fateh Ali Khan", "Sangupta", 1996, 312, "sufi", "classic,soulful"],
  ["Sohni Lagdi", "Sajjad Ali", "Sohni Lagdi", 1996, 288, "sufi", "classic,romance"],
];

export const HARYANVI_TRACKS: RawTrack[] = [
  ["Thaare Bina", "Khasa Aala Chahar", "Thaare Bina", 2020, 258, "desi folk", "romance,soulful"],
  ["Mhara Haryana", "Khasa Aala Chahar", "Mhara Haryana", 2019, 271, "desi folk", "anthem,desi"],
  ["Bewafa Yaar", "Khasa Aala Chahar", "Bewafa Yaar", 2021, 264, "ragini", "heartbreak,soulful"],
  ["Mhari Jaan", "Khasa Aala Chahar", "Mhari Jaan", 2022, 246, "desi folk", "romance,new"],
  ["Chhori Haryane Ki", "Masoom Sharma", "Chhori Haryane Ki", 2021, 232, "haryanvi pop", "dance,desi,party"],
  ["Jatt Ki Yaari", "Masoom Sharma", "Jatt Ki Yaari", 2020, 241, "haryanvi pop", "friendship,desi"],
  ["Solid Body", "Masoom Sharma", "Solid Body", 2019, 219, "dance", "party,dance"],
  ["Badnaam Chhori", "Masoom Sharma", "Badnaam Chhori", 2023, 226, "haryanvi pop", "party,new,dance"],
  ["Teri Chunari", "Masoom Sharma", "Teri Chunari", 2020, 237, "dance", "wedding,dance"],
  ["Lath Maru", "Raju Punjabi", "Lath Maru", 2018, 224, "dance", "party,dance,desi"],
  ["Teri Aankhya Ka Yo Kajal", "Raju Punjabi", "Teri Aankhya", 2017, 245, "ragini", "romance,classic"],
  ["Bhagat Singh", "Raju Punjabi", "Bhagat Singh", 2020, 268, "anthem", "desi,anthem"],
  ["Jaat Ka Attitude", "Raju Punjabi", "Jaat Ka Attitude", 2022, 213, "haryanvi pop", "flex,new"],
  ["Desi Yaar", "Raju Punjabi", "Desi Yaar", 2019, 229, "desi folk", "friendship,desi"],
  ["Gaadi", "Sumit Goswami", "Gaadi", 2020, 208, "dance", "party,dance,roadtrip"],
  ["Chhora Haryane Ka", "Sumit Goswami", "Chhora Haryane Ka", 2019, 221, "desi folk", "desi,anthem"],
  ["Aashiqui", "Sumit Goswami", "Aashiqui", 2021, 236, "haryanvi pop", "romance,soulful"],
  ["Dil Tod Ke", "Sumit Goswami", "Dil Tod Ke", 2023, 243, "ragini", "heartbreak,new"],
  ["Mhare Gaam Mein", "Sumit Goswami", "Mhare Gaam", 2021, 227, "desi folk", "desi,village"],
  ["52 Gaj Ka Daman", "Renuka Panwar", "52 Gaj Ka Daman", 2021, 214, "dance", "dance,hit,party"],
  ["Teri Yaad", "Renuka Panwar", "Teri Yaad", 2020, 249, "ragini", "heartbreak,soulful"],
  ["Bawla", "Gulzaar Chhaniwala", "Bawla", 2022, 205, "haryanvi pop", "romance,new,dance"],
  ["Chhori", "Gulzaar Chhaniwala", "Chhori", 2021, 198, "haryanvi pop", "romance,dance"],
  ["Chhori Patwari", "Aman Jaji", "Chhori Patwari", 2022, 211, "dance", "dance,party,new"],
  ["Ghagra Re", "Ruchika Jangid", "Ghagra Re", 2022, 217, "dance", "wedding,dance"],
  ["Mhare Desh Ki Chhori", "Anjali Raghav", "Mhare Desh", 2021, 233, "desi folk", "desi,anthem"],
  ["Kudi Haryane Val Di", "Yash Narvekar", "Angreji Medium", 2020, 194, "haryanvi pop", "dance,party,cinema"],
];

export const HINDI_TRACKS: RawTrack[] = [
  ["Kesariya", "Arijit Singh", "Brahmastra", 2022, 268, "bollywood", "romance,soulful,cinema"],
  ["Chaleya", "Arijit Singh", "Jawan", 2023, 207, "bollywood", "romance,dance,cinema"],
  ["Apna Bana Le", "Arijit Singh", "Bhediya", 2022, 261, "bollywood", "romance,soulful,cinema"],
  ["Sajni", "Arijit Singh", "Laapataa Ladies", 2024, 243, "indie", "romance,soulful,new"],
  ["Heeriye", "Arijit Singh", "Heeriye", 2024, 219, "pop", "romance,new,night"],
  ["O Maahi", "Arijit Singh", "Dunki", 2023, 249, "bollywood", "romance,cinema"],
  ["Tum Hi Ho", "Arijit Singh", "Aashiqui 2", 2013, 262, "bollywood", "romance,classic"],
  ["Deva Deva", "Arijit Singh", "Brahmastra", 2022, 285, "bollywood", "soulful,cinema"],
  ["Phir Aur Kya Chahiye", "Arijit Singh", "Zara Hatke Zara Bachke", 2023, 214, "bollywood", "romance,cinema"],
  ["Satranga", "Arijit Singh", "Animal", 2023, 256, "bollywood", "soulful,cinema"],
  ["Tauba Tauba", "Badshah", "Tauba Tauba", 2024, 178, "dance", "party,new,dance"],
  ["Genda Phool", "Badshah", "Genda Phool", 2020, 176, "dance", "party,dance"],
  ["Jugnu", "Badshah", "Jugnu", 2021, 191, "pop", "party,summer"],
  ["Mercy", "Badshah", "Mercy", 2024, 184, "hip-hop", "new,party"],
  ["Garmi", "Badshah", "Street Dancer 3D", 2019, 189, "dance", "party,dance,cinema"],
  ["Maan Meri Jaan", "King", "Maan Meri Jaan", 2022, 195, "indie", "romance,mood,night"],
  ["Tu Aake Dekhle", "King", "Tu Aake Dekhle", 2021, 208, "pop", "romance,night"],
  ["Husn", "Anuv Jain", "Husn", 2023, 226, "indie", "romance,soulful,acoustic"],
  ["Baarishein", "Anuv Jain", "Baarishein", 2021, 244, "indie", "romance,monsoon,acoustic"],
  ["Jo Tum Mere Ho", "Anuv Jain", "Jo Tum Mere Ho", 2024, 232, "indie", "romance,new,acoustic"],
  ["Kasoor", "Prateek Kuhad", "Kasoor", 2018, 224, "indie", "romance,acoustic,chill"],
  ["cold/mess", "Prateek Kuhad", "cold/mess", 2018, 238, "indie", "chill,late-night,acoustic"],
  ["Chogada", "Darshan Raval", "Loveyatri", 2018, 213, "bollywood", "dance,romance,cinema"],
  ["Hawa Banke", "Darshan Raval", "Hawa Banke", 2019, 227, "bollywood", "romance,chill"],
  ["Raataan Lambiyan", "Jubin Nautiyal", "Shershaah", 2021, 230, "bollywood", "romance,soulful,cinema"],
  ["Lut Gaye", "Jubin Nautiyal", "Lut Gaye", 2021, 219, "pop", "romance,party"],
  ["Lahore", "Guru Randhawa", "Lahore", 2017, 179, "pop", "party,romance"],
  ["High Rated Gabru", "Guru Randhawa", "High Rated Gabru", 2017, 183, "dance", "party,dance"],
  ["Morni Banke", "Guru Randhawa", "Morni Banke", 2018, 191, "dance", "wedding,party"],
  ["Makhna", "Yo Yo Honey Singh", "Makhna", 2019, 197, "hip-hop", "party,dance"],
  ["Blue Eyes", "Yo Yo Honey Singh", "Blue Eyes", 2014, 214, "hip-hop", "party,classic"],
  ["Dheere Dheere", "Yo Yo Honey Singh", "Dheere Dheere", 2022, 188, "pop", "party,romance"],
  ["Millionaire", "Yo Yo Honey Singh", "Glory", 2025, 194, "hip-hop", "new,flex,party"],
  ["Dilbar", "Neha Kakkar", "Satyameva Jayate", 2018, 190, "dance", "party,dance,cinema"],
  ["Udd Gaye", "Ritviz", "Udd Gaye", 2020, 176, "indie", "party,indie,dance"],
  ["Liggi", "Ritviz", "Liggi", 2020, 182, "indie", "party,indie"],
  ["Pehle Bhi Main", "Vishal Mishra", "Animal", 2023, 251, "bollywood", "soulful,cinema"],
  ["Aaj Ki Raat", "Tamannaah Bhatia", "Stree 2", 2024, 199, "dance", "party,new,cinema"],
  ["Gulabi Sadi", "Sanju Rathod", "Gulabi Sadi", 2024, 173, "dance", "dance,new,wedding"],
  ["Jeena Jeena", "Atif Aslam", "Badlapur", 2014, 228, "bollywood", "romance,cinema"],
  ["Dil Diyan Gallan", "Atif Aslam", "Tiger Zinda Hai", 2017, 261, "bollywood", "romance,cinema"],
  ["Mann Bharrya", "B Praak", "Shershaah", 2021, 245, "bollywood", "soulful,cinema"],
  ["Ghar More Pardesiya", "Shreya Ghoshal", "Kalank", 2019, 274, "bollywood", "soulful,cinema"],
  ["Sunn Raha Hai", "Ankit Tiwari", "Aashiqui 2", 2013, 268, "bollywood", "soulful,cinema"],
  ["Suraj Hua Maddham", "Sonu Nigam", "Kabhi Khushi Kabhie Gham", 2001, 306, "bollywood", "romance,classic"],
  ["Zara Sa", "KK", "Jannat", 2008, 253, "bollywood", "romance,classic"],
  ["Tum Se Hi", "Mohit Chauhan", "Jab We Met", 2007, 265, "bollywood", "romance,chill,cinema"],
  ["Bolna", "Armaan Malik", "Kapoor & Sons", 2016, 221, "bollywood", "romance,cinema"],
  ["Vaaste", "Dhvani Bhanushali", "Vaaste", 2019, 208, "pop", "romance,chill"],
  ["Kala Chashma", "Amar Arshad", "Baar Baar Dekho", 2016, 202, "dance", "party,wedding,cinema"],
];

/** Brand new 2026 releases — Punjabi. */
export const PUNJABI_2026: RawTrack[] = [
  ["God Did", "Nijjar", "God Did", 2026, 158, "hip-hop", "new,2026,flex,anthem"],
  ["Barota", "Sidhu Moose Wala", "Barota", 2026, 243, "hip-hop", "new,2026,raw,mood"],
  ["Balenci", "Shubh", "Balenci", 2026, 182, "hip-hop", "new,2026,flex,party"],
  ["Safety Off", "Shubh", "Leo", 2026, 143, "hip-hop", "new,2026,flex"],
  ["Moves", "Shubh", "Chapter IV", 2026, 160, "hip-hop", "new,2026,party,flex"],
  ["At Peace", "Karan Aujla", "At Peace", 2026, 164, "pop", "new,2026,chill,mood"],
  ["Boyfriend", "Karan Aujla", "P-POP CULTURE", 2026, 160, "pop", "new,2026,romance,party"],
  ["Thinking of You", "AP Dhillon", "Thinking of You", 2026, 180, "r&b", "new,2026,chill,late-night"],
  ["STFU", "AP Dhillon", "OKAY STFU", 2026, 174, "hip-hop", "new,2026,flex,party"],
  ["PARIS", "Guru Randhawa", "PARIS", 2026, 168, "pop", "new,2026,dance,romance"],
  ["Dealer", "Diljit Dosanjh", "Dealer", 2026, 150, "pop", "new,2026,party"],
  ["Kufar", "Diljit Dosanjh", "Kufar", 2026, 190, "folk-pop", "new,2026,anthem"],
  ["Ranjhea", "Cheema Y", "The Simpsons", 2026, 158, "pop", "new,2026,romance,mood"],
  ["California Love", "Cheema Y", "ANYWAY", 2026, 175, "hip-hop", "new,2026,party,roadtrip"],
  ["Get at Me", "Prem Dhillon", "Get at Me", 2026, 248, "hip-hop", "new,2026,raw,anthem"],
  ["Kath", "Wazir Patar", "Kath", 2026, 157, "folk", "new,2026,desi"],
  ["Dapper Dan", "Navaan Sandhu", "House Navior", 2026, 187, "pop", "new,2026,party,flex"],
  ["Deewane", "Navaan Sandhu", "House Navior", 2026, 206, "folk-pop", "new,2026,romance"],
  ["Brats", "Arjan Dhillon", "Patandar", 2026, 161, "folk", "new,2026,desi,flex"],
  ["Pind Saara Saunje", "Navi Sran", "Pind Saara Saunje", 2026, 172, "folk", "new,2026,village,desi"],
  ["Haseen", "Talwiinder", "Haseen", 2026, 174, "r&b", "new,2026,chill,romance"],
  ["One In A Million", "Jordan Sandhu", "One In A Million", 2026, 157, "pop", "new,2026,romance,wedding"],
  ["Dooron Dooron", "Paresh Pahuja", "Dooron Dooron", 2026, 215, "pop", "new,2026,soulful,romance"],
  ["Midnight Call", "Harkirat Sangha", "Interstellar", 2026, 163, "r&b", "new,2026,late-night,mood"],
  ["Jogi", "thiarajxtt", "Jogi", 2026, 174, "indie", "new,2026,chill,soulful"],
  ["Malwa Marine", "Khan Bhaini", "Genesis", 2026, 230, "hip-hop", "new,2026,flex,desi"],
  ["SHEH", "Harpreet Manna", "SHEH", 2026, 178, "dance", "new,2026,party,dance"],
  ["VELLY", "Maani Kay", "VELLY", 2026, 166, "hip-hop", "new,2026,flex"],
  ["KALA JADOO", "Armaan Gill", "KALA JADOO", 2026, 210, "pop", "new,2026,romance,party"],
  ["Check It Out", "Parmish Verma", "Check It Out", 2026, 195, "dance", "new,2026,party"],
];

/** Brand new 2026 releases — Haryanvi. */
export const HARYANVI_2026: RawTrack[] = [
  ["Bhaga Aali", "Khasa Aala Chahar", "Bhaga Aali", 2026, 193, "desi folk", "new,2026,desi,romance"],
  ["Ulti Buddhi", "Khasa Aala Chahar", "Ulti Buddhi", 2026, 170, "haryanvi pop", "new,2026,party"],
  ["Yaari Lekhe", "Khasa Aala Chahar", "Yaari Lekhe", 2026, 205, "desi folk", "new,2026,friendship"],
  ["Treat Me Special", "Rawme Hooda", "Treat Me Special", 2026, 237, "haryanvi rap", "new,2026,hip-hop,party"],
  ["Intezar", "Rawme Hooda", "Intezar", 2026, 242, "haryanvi rap", "new,2026,mood,heartbreak"],
  ["Jholi", "Shiva Choudhary", "Jholi", 2026, 156, "dance", "new,2026,dance,party"],
  ["80 Lakh", "Shiva Choudhary", "80 Lakh", 2026, 176, "haryanvi pop", "new,2026,flex"],
  ["Kabze", "Bintu Pabra", "Kabze", 2026, 168, "haryanvi pop", "new,2026,flex"],
  ["Olha Tha Ke Nachungi", "Raj Mawar", "Olha Tha Ke Nachungi", 2026, 185, "dance", "new,2026,dance,wedding"],
  ["Kilki", "Raj Mawar", "Azaad Singh", 2026, 194, "desi folk", "new,2026,cinema,soulful"],
  ["Dr. Thugni", "Raj Mawar", "Dr. Thugni", 2026, 172, "haryanvi pop", "new,2026,party"],
  ["Goli P Goli", "Rahul Puthi", "Goli P Goli", 2026, 147, "dance", "new,2026,party"],
  ["Happy Birthday", "Rahul Puthi", "Happy Birthday", 2026, 179, "haryanvi pop", "new,2026,party"],
  ["Star Beto", "Fateh Siyan", "Star Beto", 2026, 199, "desi folk", "new,2026,desi"],
  ["BANDOOK", "Swara Verma", "BANDOOK", 2026, 147, "dance", "new,2026,dance,flex"],
  ["Bhai 4", "Sawan Jhinjhania", "Bhai 4", 2026, 209, "haryanvi pop", "new,2026,friendship"],
  ["Balam", "Akshay Delu", "Balam", 2026, 171, "ragini", "new,2026,romance"],
  ["Pyar", "Harjeet Deewana", "Pyar", 2026, 205, "ragini", "new,2026,romance,soulful"],
  ["Chunni", "Renuka Panwar", "Chunni", 2026, 180, "dance", "new,2026,dance,wedding"],
  ["Love You Jaatni", "Sumit Goswami", "Love You Jaatni", 2026, 185, "haryanvi pop", "new,2026,romance"],
  ["Ram Lakhan", "Masoom Sharma", "Ram Lakhan", 2026, 191, "desi folk", "new,2026,desi"],
  ["2 Dada Part 3", "Masoom Sharma", "2 Dada Part 3", 2026, 198, "haryanvi pop", "new,2026,party"],
  ["Kesari", "Masoom Sharma", "Kesari", 2026, 203, "anthem", "new,2026,anthem,desi"],
  ["Bachpan Ka Pyaar", "Masoom Sharma", "Bachpan Ka Pyaar", 2026, 186, "ragini", "new,2026,romance"],
  ["Paani Levan Jaungi", "Aman Jaji", "Paani Levan Jaungi", 2026, 174, "dance", "new,2026,dance"],
  ["Tu Aaja Ne", "Raaji", "Tu Aaja Ne", 2026, 188, "ragini", "new,2026,romance"],
  ["Raanjhan", "Preet Sirohi", "Raanjhan", 2026, 201, "haryanvi pop", "new,2026,romance"],
  ["Tough", "Krish Rao", "Tough", 2026, 165, "haryanvi rap", "new,2026,flex"],
  ["Ram Ram Ji", "Addy Nagar", "Ram Ram Ji", 2026, 177, "desi folk", "new,2026,desi"],
];

/** Brand new 2026 releases — Hindi. */
export const HINDI_2026: RawTrack[] = [
  ["Arz Kiya Hai", "Anuv Jain", "Coke Studio Bharat", 2026, 306, "indie", "new,2026,soulful,acoustic"],
  ["Gehra Hua", "Arijit Singh", "Dhurandhar", 2026, 271, "bollywood", "new,2026,soulful,cinema"],
  ["Sitaare", "Arijit Singh", "Ikkis", 2026, 244, "bollywood", "new,2026,romance,cinema"],
  ["Tu Hi Disda", "Arijit Singh", "Bhooth Bangla", 2026, 232, "bollywood", "new,2026,dance,cinema"],
  ["Aaj Dil Shayarana", "Arijit Singh", "Aaj Dil Shayarana", 2026, 253, "pop", "new,2026,romance"],
  ["Yeh Awarapan", "Arijit Singh", "Awarapan 2", 2026, 239, "bollywood", "new,2026,mood,cinema"],
  ["Leher", "Arijit Singh", "Cocktail 2", 2026, 214, "bollywood", "new,2026,party,cinema"],
  ["Tujhko", "Arijit Singh", "Cocktail 2", 2026, 226, "bollywood", "new,2026,romance,cinema"],
  ["Tere Sang", "Arijit Singh", "Echoes Of Us", 2026, 219, "pop", "new,2026,romance"],
  ["Ek Din Title Track", "Arijit Singh", "Ek Din", 2026, 146, "bollywood", "new,2026,soulful,cinema"],
  ["Ishq Ka Fever", "Arijit Singh", "O' Romeo", 2026, 205, "bollywood", "new,2026,party,cinema"],
  ["Ghar Kab Aaoge", "Sonu Nigam", "Border 2", 2026, 268, "bollywood", "new,2026,soulful,cinema"],
  ["Ishq Da Chehra", "Diljit Dosanjh", "Border 2", 2026, 197, "bollywood", "new,2026,romance,cinema"],
  ["Hindustan Meri Jaan", "Mohit Chauhan", "Border 2", 2026, 241, "anthem", "new,2026,anthem,cinema"],
  ["Jaate Hue Lamhon", "Roop Kumar Rathod", "Border 2", 2026, 255, "bollywood", "new,2026,soulful,cinema"],
  ["Tum Ho Toh", "Vishal Mishra", "Saiyaara", 2026, 223, "bollywood", "new,2026,romance,cinema"],
  ["Barbaad", "Jubin Nautiyal", "Saiyaara", 2026, 216, "bollywood", "new,2026,heartbreak,cinema"],
  ["Kya Bataun Tujhe", "Vishal Mishra", "Pagalpan", 2026, 234, "indie", "new,2026,soulful"],
  ["Usey Kehna", "A. R. Rahman", "Tere Ishk Mein", 2026, 248, "bollywood", "new,2026,romance,cinema"],
  ["Chillgum", "Yo Yo Honey Singh", "Chillgum", 2026, 178, "dance", "new,2026,party"],
  ["Aadat", "Yo Yo Honey Singh", "51 Glorious Days", 2026, 220, "hip-hop", "new,2026,party,romance"],
  ["Laal Pari", "Yo Yo Honey Singh", "Housefull 5", 2026, 184, "dance", "new,2026,party,cinema"],
  ["Naamumkin", "Shreya Ghoshal", "Maalik", 2026, 259, "bollywood", "new,2026,soulful,cinema"],
  ["Bheegi Saree", "Shreya Ghoshal", "Param Sundari", 2026, 211, "dance", "new,2026,dance,cinema"],
  ["Aasma Aasma", "Jubin Nautiyal", "Do Deewane Seher Mein", 2026, 202, "pop", "new,2026,romance"],
  ["Ve Junoon", "Subodhh Sharma", "Awarapan 2", 2026, 245, "bollywood", "new,2026,mood,cinema"],
  ["Bandhu 2.0", "Kavita Seth", "Cocktail 2", 2026, 189, "dance", "new,2026,party,cinema"],
  ["Bewajah", "Himesh Reshammiya", "Sanam Teri Kasam 2", 2026, 264, "bollywood", "new,2026,romance,cinema"],
  ["Gone Girl", "Badshah", "Gone Girl", 2026, 176, "hip-hop", "new,2026,party"],
  ["Tu Aashiqui Hai Meri", "Payal Dev", "Tu Aashiqui Hai Meri", 2026, 208, "pop", "new,2026,romance"],
  ["Tera Naam Lete Hain", "Nishtha Sharma", "Tera Naam Lete Hain", 2026, 195, "pop", "new,2026,romance"],
  ["Har Har Mahadev", "Sachet Tandon", "Har Har Mahadev", 2026, 229, "sufi", "new,2026,devotional"],
  ["Kabhi Shaam Dhale", "Jaani", "Kabhi Shaam Dhale", 2026, 217, "indie", "new,2026,soulful,night"],
  ["Ae Ajnabee", "Aditya Rikhari", "Ae Ajnabee", 2026, 199, "indie", "new,2026,mood,night"],
  ["Khat", "Navjot Ahuja", "Khat", 2026, 187, "indie", "new,2026,romance"],
  ["Dilbar Ki Aankhon Ka", "Rashmeet Kaur", "Thamma", 2026, 193, "dance", "new,2026,dance,cinema"],
  ["Dhurandhar Title Track", "Hanumankind", "Dhurandhar", 2026, 155, "hip-hop", "new,2026,anthem,cinema"],
];

export const NEWEST_RELEASE_YEAR = 2026;

export const LANGUAGE_TRACKS: Record<"punjabi" | "haryanvi" | "hindi", RawTrack[]> = {
  punjabi: [...PUNJABI_TRACKS, ...PUNJABI_2026],
  haryanvi: [...HARYANVI_TRACKS, ...HARYANVI_2026],
  hindi: [...HINDI_TRACKS, ...HINDI_2026],
};

export const CATALOG_SIZE = Object.values(LANGUAGE_TRACKS).reduce(
  (total, list) => total + list.length,
  0,
);

/** Placeholder preview audio used for every track (16 looping demo clips). */
export const PREVIEW_AUDIO_COUNT = 16;
export function previewAudioUrl(index: number): string {
  return `https://www.soundhelix.com/examples/mp3/SoundHelix-Song-${(index % PREVIEW_AUDIO_COUNT) + 1}.mp3`;
}

export const CURATED_PLAYLISTS: {
  name: string;
  description: string;
  match: (language: string, moods: string, year: number) => boolean;
}[] = [
  {
    name: "Class of 2026",
    description: "Everything that dropped this year — Punjab, Haryana and Bollywood in one queue.",
    match: (_l, m, y) => y >= 2026 || m.includes("2026"),
  },
  {
    name: "Fresh Punjabi Drops",
    description: "Brand new gaane from the Doaba to Toronto — straight off the 2024+ run.",
    match: (l, _m, y) => l === "punjabi" && y >= 2023,
  },
  {
    name: "Haryanvi Dhamaka",
    description: "Dholak, dhamal and full volume. The loudest chhoris of Haryana.",
    match: (l, m) => l === "haryanvi" && /dance|party|desi/.test(m),
  },
  {
    name: "Bollywood Romance",
    description: "Slow-burn ishq — Arijit, Atif, Shreya and the rest of the heart.",
    match: (l, m) => l === "hindi" && /romance|soulful/.test(m),
  },
  {
    name: "Late Night Drive",
    description: "Bass low, windows down. Punjabi R&B meets Hindi indie.",
    match: (_l, m) => /late-night|night|chill|mood/.test(m),
  },
  {
    name: "Gym & Attitude",
    description: "Flex tracks only. 52 Bars, Levels, King Shit and friends.",
    match: (_l, m) => /flex|raw|anthem/.test(m),
  },
  {
    name: "Wedding Season",
    description: "Laung laachi, ghagra re, morni banke — everything the baraat needs.",
    match: (_l, m) => /wedding|bhangra/.test(m),
  },
  {
    name: "Desi Heartbreak",
    description: "Bewafa yaar, no love, dil tod ke. Tissue box not included.",
    match: (_l, m) => /heartbreak/.test(m),
  },
  {
    name: "Timeless Classics",
    description: "The songs every family gathering still plays on loop.",
    match: (_l, _m, y) => y <= 2013,
  },
];
